version: '3.8'

services:
  # MongoDB Database for Development
  mongodb-dev:
    image: mongo:7.0
    container_name: restaurant-pos-db-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-restaurant_pos_dev}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - restaurant-pos-dev-network

  # Backend API for Development
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: restaurant-pos-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb-dev:27017/${MONGO_DATABASE:-restaurant_pos_dev}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      FRONTEND_URL: http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_dev_logs:/app/logs
    networks:
      - restaurant-pos-dev-network
    command: npm run dev

networks:
  restaurant-pos-dev-network:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local
  backend_dev_logs:
    driver: local
